# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Beer Club
tagline:          'A gentlemen club'
description:      'Canberra's fellow beer lovers'
url:              http://beerclubcbr.github.io
# baseurl:          / # Deprecated

# author:
#   name:           'Marcus'
#   url:            https://elgandoz.github.io/

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/beerclubcbr/beerclubcbr.github.io
