# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CBR Beer Club
tagline:          'A gentlemen club'
description:      ''
url:              https://beerclubcbr.github.io/
baseurl:          /

# author:
#   name:           'Marcus'
#   url:            https://elgandoz.github.io/

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/beerclubcbr/beerclubcbr.github.io
